# Generated by Django 2.0 on 2017-12-09 01:25
from decimal import Decimal
from django.db import migrations, models
from django.utils import timezone


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    InterestRate = apps.get_model("calculator", "InterestRate")
    db_alias = schema_editor.connection.alias
    InterestRate.objects.using(db_alias).create(rate=Decimal("0.025"))


def reverse_func(apps, schema_editor):
    # remove the initial interest rate of 2.5%
    InterestRate = apps.get_model("calculator", "InterestRate")
    db_alias = schema_editor.connection.alias
    InterestRate.objects.using(db_alias).filter(rate=Decimal("0.025")).order_by('since')[0].delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=7, max_digits=8)),
                ('since', models.DateTimeField(default=timezone.now)),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
